dist: xenial

language: ruby
rvm:
  - 2.3.1
env: SECRET_KEY_BASE=859384 RUN_SLOW_TESTS=true

before_install:
  - gem install bundler:1.17.3

before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
  - docker pull openaustralia/buildstep

after_success:
  - bundle exec codeclimate-test-reporter

services:
  - docker
  - redis
  - mysql
