# Install required roles with
# cd provisioning
# ansible-galaxy install -r requirements.yml -p roles

- src: azavea.elasticsearch
  version: 0.1.0

- src: azavea.java
  # Latest version as of Jan 2018
  version: 0.6.1

# Commenting out because our local version has been modified from the original
# - src: nickhammond.logrotate
#   version: 71b0ab39066f2dfd5b2701205cf398e97cda52c2
